apiVersion: v1 
kind: Pod
metadata: 
 name: namitpod1 # must be unique
 labels:
  x: namitapp
spec:
 containers:
  - name: namitc1  # this can be same for everyone
    image: nginx
    ports:
     - containerPort: 80  # same as docker file port    
  
---       
apiVersion: v1
kind: Service
metadata:
        name: namitpod1svc
spec:
  ports:
  - name: myport
    port: 80
    protocol: TCP
    targetPort: 80  
  selector:
   x: namitapp #  same as your pod label
  type: NodePort
