apiVersion: v1
kind: Service
metadata:
        name: namitpod1svc
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80  
  selector:
   x: namitapp #  same as your pod label
   type: NodePort
