FROM  python
#  from  will pull  python  docker image  from  docker hub
COPY  namit1.py  /tmp/namit1.py
#  from  host  to  docker  image  copy
CMD  python   /tmp/namit1.py
#  this will be  default  parent  process
